# References {-}

1. A&E Television Networks. (2011, March 15). Pilot sully Sullenberger performs "Miracle on the Hudson". History.com. Retrieved November 1, 2021, from https://www.history.com/this-day-in-history/sully-sullenberger-performs-miracle-on-the-hudson.

2. FAA Wildlife Strike Database. (n.d.). Retrieved July 15, 2021, from https://wildlife.faa.gov/home. 

3. Tedrow, Christine A. Dec. 1998, https://vtechworks.lib.vt.edu/bitstream/handle/10919/40926/tedrow.pdf?sequence=1. 

4. Dolbeer, R. A. (2011). Increasing trend of damaging bird strikes with aircraft outside the airport boundary: Implications for mitigation measures. Retrieved October 10, 2021, from https://digitalcommons.usu.edu/hwi/vol5/iss2/12/. 

5. Fernandez, E., Gaffney, J., Blackwell, B., & Baumhardt, P. (2011). Bird strikes and aircraft fuselage color: A correlational study. Retrieved November 1, 2021, from https://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=1180&context=hwi. 

6. Ahmad, M. (2019, February 6). BIRD-STRIKE AIRCRAFT ACCIDENTS AND THEIR PREVENTION. Retrieved October 11, 2021, from https://www.researchgate.net/publication/330900871_BIRD-STRIKE_AIRCRAFT_ACCIDENTS_AND_THEIR_PREVENTION.

7. Nilsson, C., La Sorte, F., Dokter, A., Horton, K., Van Doren, B., Kolodzinski, J., Shamoun-Baranes, J., & Farnsworth, A. (2021, August 18). Bird strikes at commercial airports explained by citizen science and Weather Radar Data. Retrieved November 1, 2021, from https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2664.13971.


 
 


